export const AUTHLOG_START = "AUTHLOG_START";
export const AUTHLOG_SUCCESS = "AUTHLOG_SUCCESS";
export const AUTHLOG_FAIL = "AUTHLOG_FAIL";
export const AUTHREG_START = "AUTHREG_START";
export const AUTHREG_SUCCESS = "AUTHREG_SUCCESS";
export const AUTHREG_FAIL = "AUTHREG_FAIL";
export const WRONG_PASSWORDS = "WRONG_PASSWORDS";
export const LOGOUT = "LOGOUT";

export const GET_PLAYERS = "GET_PLAYERS";
export const FETCH_PLAYERS_FAILED = "FETCH_PLAYERS_FAILED";

export const GET_GROUPS = "GET_GROUPS";
export const FETCH_GROUPS_FAILED = "GET_GROUPS_FAILED";
export const GROUP_FOUND = "GROUP_FOUND";


export const AVAILABLE_COMPETITIONS = "AVAILABLE_COMPETITIONS";