export const AUTHLOG_START = "AUTHLOG_START";
export const AUTHLOG_SUCCESS = "AUTHLOG_SUCCESS";
export const AUTHLOG_FAIL = "AUTHLOG_FAIL";
export const AUTHREG_START = "AUTHREG_START";
export const AUTHREG_SUCCESS = "AUTHREG_SUCCESS";
export const AUTHREG_FAIL = "AUTHREG_FAIL";
export const WRONG_PASSWORDS = "WRONG_PASSWORDS";
export const LOGOUT = "LOGOUT";


export const GET_GROUPS = "GET_GROUPS";
export const FETCH_GROUPS_FAILED = "GET_GROUPS_FAILED";
export const GROUP_FOUND = "GROUP_FOUND";


export const AVAILABLE_COMPETITIONS = "AVAILABLE_COMPETITIONS";

export const SET_GROUP = "SET_GROUP";
export const GET_PLAYERS = "GET_PLAYERS";


export const SET_MATCHES = "SET_MATCHES";

export const UPDATE_BETS = "UPDATE_BETS";
export const INCREASE_OR_DECREASE = "INCREASE_OR_DECREASE";

export const SENDING_BET_START = "SENDING_BET_START";
export const SENDING_BET_SUCCESS = "SENDING_BET_SUCCESS";


